name: Java push demo

on:
  push:
    branches:
      - main
jobs:
  java-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution:  'temurin'
          java-version:  '17'

      - name: check Java Version
        run:  java-version

      - name: compile Java Version
        run:  javac HelloWorld.java

      - name: Run Java Application
        run: java HelloWorld
